### ISSUE TITLE
An ability to add an error to an error report

### ISSUE THREAD

**Issue by annabokhan** [cisco-open/stated#31]
## Problem Statement

In order to enable unit testing, each failed test case needs to record an error in some global report, while continuing the execution of all the tests in a suite. That report needs to be returned in the end of test case execution

## Proposed Solution

Add a new function, i.e. reportError(string name), which appends a new error to the report.
.out should return the report if there are any errors in it. This could be an option triggered by an argument

**Comment by geoffhendrey** [comment]
So the one thing I would add/modify is that the template output object (.out) is the "domain object". We don't want anyone to have to model errorReport in their domain. So `errorReport` is a field of the templateProcessor, alongside `output`.

**Comment by geoffhendrey** [comment]
The errorReport function is done and documented. We won't return the report at the end of execution. That kind of violates a lot of principles we have in place for the REPL. We will go with the existing strategy of .errors from REPL to view the error report. Same for Orion - they explicitly check templateProcessor.errorReport

**Comment by geoffhendrey** [comment]
closing as done
